### ISSUE TITLE
Plugin does not load.

### ISSUE THREAD

**Issue by AAigars** [McMackety/velocity-queue#1]
Proxy: Velocity 1.1.2
Version: Latest Release
Stacktrace:
```
[12:58:36 ERROR]: Can't create plugin velocityqueue
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, kotlin.jvm.KotlinReflectionNotSupportedError: Kotlin reflection implementation is not found at runtime. Make sure you have kotlin-reflect.jar in the classpath
  at org.mcmackety.vqueue.QueuePlugin.<init>(QueuePlugin.kt:26)
  at com.velocitypowered.proxy.plugin.loader.java.VelocityPluginModule.configure(VelocityPluginModule.java:31)
  while locating org.mcmackety.vqueue.QueuePlugin

1 error
        at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:226) ~[server.jar:1.1.2]
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1097) ~[server.jar:1.1.2]
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1131) ~[server.jar:1.1.2]
        at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.createPlugin(JavaPluginLoader.java:104) ~[server.jar:1.1.2]
        at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:135) ~[server.jar:1.1.2]
        at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:268) ~[server.jar:1.1.2]
        at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:210) ~[server.jar:1.1.2]
        at com.velocitypowered.proxy.Velocity.main(Velocity.java:55) ~[server.jar:1.1.2]
Caused by: kotlin.jvm.KotlinReflectionNotSupportedError: Kotlin reflection implementation is not found at runtime. Make sure you have kotlin-reflect.jar in the classpath
        at kotlin.jvm.internal.ClassReference.error(ClassReference.kt:84) ~[?:?]
        at kotlin.jvm.internal.ClassReference.getConstructors(ClassReference.kt:21) ~[?:?]
        at kotlin.reflect.jvm.ReflectJvmMapping.getKotlinFunction(ReflectJvmMapping.kt:146) ~[?:?]
        at com.fasterxml.jackson.module.kotlin.KotlinNamesAnnotationIntrospector.findKotlinParameterName(KotlinNamesAnnotationIntrospector.kt:125) ~[?:?]
        at com.fasterxml.jackson.module.kotlin.KotlinNamesAnnotationIntrospector.findImplicitPropertyName(KotlinNamesAnnotationIntrospector.kt:33) ~[?:?]
        at com.fasterxml.jackson.databind.introspect.AnnotationIntrospectorPair.findImplicitPropertyName(AnnotationIntrospectorPair.java:490) ~[?:?]
        at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._addCreatorParam(POJOPropertiesCollector.java:512) ~[?:?]
        at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._addCreators(POJOPropertiesCollector.java:492) ~[?:?]
        at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.collectAll(POJOPropertiesCollector.java:327) ~[?:?]
        at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getJsonValueAccessor(POJOPropertiesCollector.java:203) ~[?:?]
        at com.fasterxml.jackson.databind.introspect.BasicBeanDescription.findJsonValueAccessor(BasicBeanDescription.java:252) ~[?:?]
        at com.fasterxml.jackson.databind.ser.BasicSerializerFactory.findSerializerByAnnotations(BasicSerializerFactory.java:396) ~[?:?]
        at com.fasterxml.jackson.databind.ser.BeanSerializerFactory._createSerializer2(BeanSerializerFactory.java:216) ~[?:?]
        at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:165) ~[?:?]
        at com.fasterxml.jackson.databind.SerializerProvider._createUntypedSerializer(SerializerProvider.java:1474) ~[?:?]
        at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1422) ~[?:?]
        at com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:521) ~[?:?]
        at com.fasterxml.jackson.databind.SerializerProvider.findTypedValueSerializer(SerializerProvider.java:799) ~[?:?]
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:308) ~[?:?]
        at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4409) ~[?:?]
        at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:3604) ~[?:?]
        at org.mcmackety.vqueue.config.YAMLParse.writeFile(YAMLParse.kt:29) ~[?:?]
        at org.mcmackety.vqueue.QueuePlugin.<init>(QueuePlugin.kt:65) ~[?:?]
        at org.mcmackety.vqueue.QueuePlugin$$FastClassByGuice$$f0e28011.newInstance(<generated>) ~[?:?]
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89) ~[server.jar:1.1.2]
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[server.jar:1.1.2]
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[server.jar:1.1.2]
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306) ~[server.jar:1.1.2]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[server.jar:1.1.2]
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168) ~[server.jar:1.1.2]
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39) ~[server.jar:1.1.2]
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1094) ~[server.jar:1.1.2]
```

**Comment by McMackety** [comment]
Are you using Java 8 or Java 11?

**Comment by McMackety** [comment]
Scratch that, seems like using shadow to minimize the Jar broke everything. Fixed it with the newest commit, reply here if the new release doesn't fix it.

**Comment by McMackety** [comment]
Here is the release that fixes that: https://github.com/McMackety/velocity-queue/releases/tag/v1.0.1
