### ISSUE TITLE
Can't create plugin velocityqueue

### ISSUE THREAD

**Issue by Xemorr** [McMackety/velocity-queue#18]
[23:28:52 ERROR]: Can't create plugin velocityqueue
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, java.lang.IllegalAccessError: class org.mcmackety.vqueue.queue.LocalQueue (in unnamed module @0x37ed010a) cannot access class sun.awt.Mutex (in module java.desktop) because module java.desktop does not export sun.awt to unnamed module @0x37ed010a
  at org.mcmackety.vqueue.QueuePlugin.<init>(QueuePlugin.kt:33)
  at com.velocitypowered.proxy.plugin.loader.java.VelocityPluginModule.configure(VelocityPluginModule.java:48)
  while locating org.mcmackety.vqueue.QueuePlugin

1 error
        at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:226) ~[velocity-1.1.8.jar:1.1.8]
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1097) ~[velocity-1.1.8.jar:1.1.8]
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1131) ~[velocity-1.1.8.jar:1.1.8]
        at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.createPlugin(JavaPluginLoader.java:121) ~[velocity-1.1.8.jar:1.1.8]
        at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:152) ~[velocity-1.1.8.jar:1.1.8]
        at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:285) ~[velocity-1.1.8.jar:1.1.8]
        at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:227) ~[velocity-1.1.8.jar:1.1.8]
        at com.velocitypowered.proxy.Velocity.main(Velocity.java:75) ~[velocity-1.1.8.jar:1.1.8]
Caused by: java.lang.IllegalAccessError: class org.mcmackety.vqueue.queue.LocalQueue (in unnamed module @0x37ed010a) cannot access class sun.awt.Mutex (in module java.desktop) because module java.desktop does not export sun.awt to unnamed module @0x37ed010a
        at org.mcmackety.vqueue.queue.LocalQueue.<init>(LocalQueue.kt:19) ~[?:?]
        at org.mcmackety.vqueue.QueuePlugin.createQueue(QueuePlugin.kt:371) ~[?:?]
        at org.mcmackety.vqueue.QueuePlugin.<init>(QueuePlugin.kt:76) ~[?:?]
        at org.mcmackety.vqueue.QueuePlugin$$FastClassByGuice$$f0e28011.newInstance(<generated>) ~[?:?]
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89) ~[velocity-1.1.8.jar:1.1.8]
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[velocity-1.1.8.jar:1.1.8]
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[velocity-1.1.8.jar:1.1.8]
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306) ~[velocity-1.1.8.jar:1.1.8]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[velocity-1.1.8.jar:1.1.8]
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168) ~[velocity-1.1.8.jar:1.1.8]
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39) ~[velocity-1.1.8.jar:1.1.8]
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1094) ~[velocity-1.1.8.jar:1.1.8]
        ... 6 more

Running Java 16 if that's relevant

**Comment by McMackety** [comment]
Try downgrading to Java 11, I had to add a Mutex to the Queue due to the multi-threaded event loop Velocity has, I can switch it out for something else soon but in the short term you will need to downgrade.
