### ISSUE TITLE
Does not work on Java 8

### ISSUE THREAD

**Issue by Cubxity** [McMackety/velocity-queue#2]
Java version: `1.8.0_252`
Velocity version: `1.1.2`
Stacktrace:
```
java.lang.NoSuchMethodError: java.util.Optional.isEmpty()Z
at org.mcmackety.vqueue.QueuePlugin.isQueuedServer(QueuePlugin.kt:221) ~[?:?]
at org.mcmackety.vqueue.QueuePlugin.onPlayerSwitchServer(QueuePlugin.kt:147) ~[?:?]
at net.kyori.event.asm.generated.12d8020061.QueuePlugin-onPlayerSwitchServer-ServerPreConnectEvent-8.invoke(Unknown Source) ~[?:?]
at net.kyori.event.method.SimpleMethodSubscriptionAdapter$MethodEventSubscriber.invoke(SimpleMethodSubscriptionAdapter.java:148) ~[bungeecord.jar:1.1.2]
at net.kyori.event.SimpleEventBus.post(SimpleEventBus.java:107) ~[bungeecord.jar:1.1.2]
at com.velocitypowered.proxy.plugin.VelocityEventManager.fireEvent(VelocityEventManager.java:137) ~[bungeecord.jar:1.1.2]
at com.velocitypowered.proxy.plugin.VelocityEventManager.lambda$fire$1(VelocityEventManager.java:119) ~[bungeecord.jar:1.1.2]
at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604) ~[?:1.8.0_252]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_252]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_252]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252] 
```

**Comment by McMackety** [comment]
I’ll go ahead a switch it to a Java 8 compatible method tonight, though Velocity soon will require Java 11 so you should switch.

**Comment by McMackety** [comment]
Just went ahead and fixed this on the latest commit, waiting for it to build then I'll make a new release.
